// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webApi.Models
{
    public partial class Customer
    {
        public Customer()
        {
            Addresses = new HashSet<Address>();
            Invoices = new HashSet<Invoice>();
            LineItems = new HashSet<LineItem>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long? Phone { get; set; }

        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<LineItem> LineItems { get; set; }
    }
}